### ISSUE TITLE
Failed list got updated

### ISSUE THREAD

**Issue by cailiangliang765** [ShixiangWang/DoAbsolute#1]
`DoAbsolute(Seg = Seg3, platform = "SNP_6.0", copy.num.type = "total", results.dir = "myabsolutecnv3", nThread = 4, keepAllResult = TRUE, verbose = TRUE)`
o Spliting seg data of samples to different files...
oo Processing sample  1 ...
oo Processing sample  2 ...
oo Processing sample  3 ...
oo Processing sample  4 ...
oo Processing sample  5 ...
oo Processing sample  6 ...
oo Processing sample  7 ...
oo Processing sample  8 ...
oo Processing sample  9 ...
oo Processing sample  10 ...
oo Processing sample  11 ...
o Spliting seg data of samples done.
o Running RunAbsolute...
o RunAbsolute done. Retrieving results...
o Running Absolute summarize...
[1] "Failed list got updated 1"
-[1] "Failed list got updated 2"
-[1] "Failed list got updated 3"
-[1] "Failed list got updated 4"
-[1] "Failed list got updated 5"
-[1] "Failed list got updated 6"
-[1] "Failed list got updated 7"
-[1] "Failed list got updated 8"
-[1] "Failed list got updated 9"
-[1] "Failed list got updated 10"
-[1] "Failed list got updated 11"
-Error in mode.ent[i] <- mtab[ix, "entropy"] : replacement has length zero

**Comment by HengqiLiu** [comment]
I have the same error as you, could you please tell me how to solve it.
