### ISSUE TITLE
批处理报错问题处理

### ISSUE THREAD

**Issue by ShixiangWang** [ShixiangWang/DoAbsolute#10]
一般需要修改的代码在 https://github.com/ShixiangWang/DoAbsolute/blob/edd359dad5657b91af7981a1e78dc6c1b25b8c69/R/DoAbsolute.R#L309

后续问题在这里跟进 @taoziyu97

**Comment by taoziyu97** [comment]
重新克隆新的仓库内容后仍然在部分癌症中出现如下报错：
```
Error in { : task 4 failed - "No mutations left"
Calls: DoAbsolute -> %dopar% -> <Anonymous>
Execution halted
```
出现报错的癌症分别为：GBM, HNSC, KIRC, KIRP, LUAD, LUSC, PRAD, UCEC, SARC, BRCA, COAD

**Comment by ShixiangWang** [comment]
@taoziyu97 我修改了可能的错误，并实施对报错样本进行跳过的举措，你在clone好的目录下使用 `git pull` 拉取更新，然后安装进行重试。

如果不出意外，任何错误样本都会进行跳过，我们在全部跑完后再处理报错样本。报错的信息都会记录在输出目录的 `error.log` 下，一个癌症类型处理完后查看下相应的文件。

**Comment by ShixiangWang** [comment]
你尽快跑起来，明天早上看下效果怎么样，然后在这里回复我。

**Comment by taoziyu97** [comment]
在跑了，出结果后我在这里回复。

**Comment by ShixiangWang** [comment]
结果有出来吗 有没有报错

**Comment by taoziyu97** [comment]
之前出问题的样本还在跑，我早上看一下结果，另外，针对更改`primary disease`和`max.as.seg.count`参数的文件，成功运行完脚本后没有文件输出，我已经检查过输出文件目录没有问题，这是为什么？

**Comment by ShixiangWang** [comment]
看下设置的临时目录？所有输出信息粘贴下

**Comment by taoziyu97** [comment]
我检查了下文件日期，发现新文件覆盖掉了旧文件，输出文件的目录按照r脚本中的目录输出，pbs设置的输出目录和r脚本输出目录不一致导致pbs目录下没有文件输出。

另外，出问题的样本结果还没出来，出来后我会即刻回复。

**Comment by ShixiangWang** [comment]
你知道哪个样本报错了？如果是这样怎么不用报错的样本做测试呢？

**Comment by ShixiangWang** [comment]
我修改了下代码 <https://github.com/ShixiangWang/DoAbsolute/commit/cfea90551c76c401ca08e9e167006f14543b62b2>，增加了一开始创建输出目录。然后测试了下报错，能够正常得到 error.log 文件，错误样本全部会被跳过。

**Comment by taoziyu97** [comment]
> 你知道哪个样本报错了？如果是这样怎么不用报错的样本做测试呢？
报错的样本正在做测试，另外之前primary disease参数重新设置成pan-cancer和max.as.seg.count参数设置存在问题，所以需要对所有的样本进行重新跑，我的理解没错吗？这是两批工作。

**Comment by ShixiangWang** [comment]
是的，你代码里面是怎么设置的？？

**Comment by taoziyu97** [comment]
师兄这个报错样本新的报错是啥意思？
```
Error in { : task 10 failed - "cannot open the connection"
Calls: DoAbsolute -> %dopar% -> <Anonymous>
Execution halted
```

**Comment by taoziyu97** [comment]
> 是的，你代码里面是怎么设置的？？

primary disease = NA， max.as.seg.count = 100000

**Comment by ShixiangWang** [comment]
这个是目录不存在导致问题，应该是之前报错的样本有这个问题吧，你更新下github上的代码然后重新跑一下。

后面这个设置看起来没有问题，是存在什么报错？就是没有结果吗？

**Comment by taoziyu97** [comment]
> 这个是目录不存在导致问题，应该是之前报错的样本有这个问题吧，你更新下github上的代码然后重新跑一下。
> 
> 后面这个设置看起来没有问题，是存在什么报错？就是没有结果吗？

后面这个没有报错，前面目录的问题我重跑一下。

**Comment by ShixiangWang** [comment]
目前有什么问题吗 @taoziyu97

**Comment by taoziyu97** [comment]
为什么更新完代码跑仍然会有no connection 报错，我使用git pull在从git上clone下来的doabsolute目录下进行了更新，是我操作有问题吗？

**Comment by ShixiangWang** [comment]
@taoziyu97 你来找我下，这个问题我来处理吧

**Comment by ShixiangWang** [comment]
目前代码运行情况怎么样？

**Comment by taoziyu97** [comment]
无报错

**Comment by ShixiangWang** [comment]
Close it for now.
