### ISSUE TITLE
Error message: bad restore file magic number

### ISSUE THREAD

**Issue by zhumengyan** [ShixiangWang/DoAbsolute#12]
Thanks for your R package!
I encounter an error, "Error message: bad restore file magic number (file may be corrupted) -- no data loaded".
Could you give me some help ?

**Comment by ShixiangWang** [comment]
@zhumengyan I haven't encountered this situation before. Could you report your commands and output messages in details?

By the way, could you run the example shown [here](https://github.com/ShixiangWang/DoAbsolute#example) to see how it works?

**Comment by zhumengyan** [comment]
> @zhumengyan I haven't encountered this situation before. Could you report your commands and output messages in details?
> 
> By the way, could you run the example shown [here](https://github.com/ShixiangWang/DoAbsolute#example) to see how it works?

Thanks for your quick reply!
The example you provide runs properly.

The error of my data:
`
[1] "Capping 0 segs at tCR = 5.0"
[1] "Expected copy-ratio = 0.94973"
[1] "Mode flag is NA, not generating plots. Sample has failed ABSOLUTE"
[1] "Capping 0 segs at tCR = 5.0"
[1] "Expected copy-ratio = 0.90187"
[1] "Mode flag is NA, not generating plots. Sample has failed ABSOLUTE"

-> RunAbsolute done. Retrieving results...
-> Checking result files...
-> Checked.
-> Removed previous temp review result directory.
-> Running Absolute summarize...
[1] "Failed list got updated 1"
-[1] "Failed list got updated 2"
-Error in mode.ent[i] <- mtab[ix, "entropy"] : replacement has length zero
`

**Comment by zhumengyan** [comment]
I use CNVkit results instead of VarScan2 results, then it's OK
