### ISSUE TITLE
计算肿瘤克隆突变负荷、亚克隆突变负荷

### ISSUE THREAD

**Issue by DrZhaoJie** [ShixiangWang/DoAbsolute#14]

**Comment by ShixiangWang** [comment]
@DrZhaoJie 在输出结果中应该有一个 Maf 目录，下面的文件里都有标定每个突变的 ccf，ccf 接近 1 的是克隆突变，其他就可以看作亚克隆。 另外 LOH 则看 seg 目录下的绝对拷贝数值，我不记得会不会 report major allele 和 minor allel 的拷贝数，一般 minor allele 拷贝数为0，而总拷贝数大于0就是 LOH。

**Comment by DrZhaoJie** [comment]
王老师，您好！
这是我运行您的测试代码得到的maf.txt和segtab.txt文件，有几个问题请教您！谢谢！
（1）肿瘤内异质性ITH是哪个指标呢？
（2）请问maf.txt中old_cancer_cell_fraction和cancer_cell_fraction以哪一列结果为准呢？是否cancer_cell_fraction列中数值为1的为克隆性突变，不为1的为亚克隆突变？那么计算这个样本的克隆性突变负荷为cancer_cell_fraction == 1的基因的总个数？亚克隆突变负荷为cancer_cell_fraction != 1的基因的总个数？
（3）segtab.txt没有看到您说的信息呢，某个样本的LOH评分如何计算呢？
（4）还想请教一下这个结果中除了purity ploidy ITH LOH 克隆和亚克隆突变负荷，还有什么指标可以挖掘呢？谢谢您的解答！
[DoAbsolute测试结果.zip](https://github.com/ShixiangWang/DoAbsolute/files/5429501/DoAbsolute.zip)

**Comment by ShixiangWang** [comment]
1. ITH 是一个概念，有很多不同角度的指标，这个得根据你自己的研究兴趣理解。
2. 应该是 cancer_cell_fraction，segment文件也有这样的一列。我看到有一个 subclonal 的列已经标出来克隆状态了。
3. DoAbsolute 目前进行的都是总拷贝，并没有包括 allele specific copy number 信息，这个 ABSOLUTE 本身是支持这个功能的，不过比较复杂，你可以去看 firehose 上的介绍。你可以另外找些软件去得到这个信息就可以判断 loh了。
4. 我也不清楚，对这个研究比较少，这个你需要自己多看相关文献，例如 https://link.springer.com/article/10.1186/gb-2013-14-7-r80

**Comment by DrZhaoJie** [comment]
Hi, 王老师，请问一下，TCGA的数据是不是无法计算 major allele 和 minor allele copy number? 因为没有allele数据？
