### ISSUE TITLE
Running DoAbsolute with or without normal data

### ISSUE THREAD

**Issue by clersdom** [ShixiangWang/DoAbsolute#16]
I have a few doubts regarding DoAbsolute and how to interpret the results:

1) Would the results from running DoAbsolute be more accurate when running it with normal paired data, as in your example? Or the function will output the copy number values for each individual sample, so that is copy number values foe each tumour and normal sample?

2) And from the output from DoAbsolute, what is the `copy_ratio` column referring to?
3) The Absolute Copy number values obtained by running DoAbsolute (`modal_cn` column) can then be used to run sigminer. But I am wondering if the below interpreation is correct:

0-homozygous deletion
1- heterozygous deletion/LOH
2- wt allele
3-heterozygous amplification
4-homozygous amplification

How would a 5 in absolte copy number value be interpreted as? Would it be the case for aneuploid cases that have had genome doubling events, and thus have another copy of that allele?

Thank you

**Comment by ShixiangWang** [comment]
@clersdom I will reply your questions point by point,

1. In my view, ABSOLUTE don't need normal samples to promote accuracy. The samples shown in example are just used to show the DoAbsolute usage. I obtained them from GenePattern documentation.
2. `copy_ratio` generally refers to `log2(tumor_copy/normal_copy)`, it is a common column in `.seg` file, you can validate the formula by yourself.
3. `modal_cn` refers to integer copy number. There are genes have >4 copies in cancer genome, e.g. ecDNA, not just 5 cases as you posted. The `2`, `3` and `4` copies may have cases what you not think, e.g. a gene can drop one allele and amplify 3 alleles to get 4.  You need to get allele-specific copy number to know the exact copy number states.

Please read doc https://www.genepattern.org/modules/docs/ABSOLUTE to know the ABSOLUTE in details and ask them if you have questions about result and implementation of ABSOLUTE. The DoAbsolute is just a wrapper, it doesn't change any result.

**Comment by ShixiangWang** [comment]
I will close this for now. Please free to reopen it if you got further problems in this issue.
