### ISSUE TITLE
请教absolute计算ITH的问题

### ISSUE THREAD

**Issue by DrZhaoJie** [ShixiangWang/DoAbsolute#17]
王老师：
       您好！试着运行了一下您的DoAbsolute包，输出结果里看到clonal subclonal CCF等信息，想请教一下absolute方法计算的ITH和pyclone计算的ITH差别大吗？谢谢您！

**Comment by ShixiangWang** [comment]
这个不知道。你可以自己拿些样本测试看看。

**Comment by ShixiangWang** [comment]
close due to long time without reponse
