### ISSUE TITLE
Allele specific Copy number进行absolute运算

### ISSUE THREAD

**Issue by DrZhaoJie** [ShixiangWang/DoAbsolute#18]

**Comment by ShixiangWang** [comment]
补充你邮件里面发的图：

![image](https://user-images.githubusercontent.com/25057508/120931445-221ce080-c724-11eb-9b35-da9003f08501.png)

**Comment by ShixiangWang** [comment]
你可以对比下包内提供的示例文件：https://github.com/ShixiangWang/DoAbsolute/blob/master/inst/extdata/SNP6_metastatic_tumor.seg.txt

基本是一一对应的，你修改下列名就好了，可以使用DoAbsolute这个包。

![image](https://user-images.githubusercontent.com/25057508/120931484-56909c80-c724-11eb-8aae-767d28b9a173.png)

**Comment by DrZhaoJie** [comment]
是的王老师，我是修改成这样的列名的，所以不用在意他文件的描述“description: Somatic CNA data (Allele-specific Copy number Estimate from Tumor/normal Sequencing from facets)”是吗？谢谢！

**Comment by ShixiangWang** [comment]
你提供的截图并没有等位基因的拷贝数值（Allele-specific Copy number），`seg.mean`就是总拷贝。目前我看来不用在意。

**Comment by DrZhaoJie** [comment]
好的，谢谢王老师！
