### ISSUE TITLE
Supporting platform of DoAbsolute

### ISSUE THREAD

**Issue by daisyyr** [ShixiangWang/DoAbsolute#19]
Hi~Thanks so much for developing such a useful tool. 
I have a question about the usage of the function` DoAbsolute`. From the function help page,  I found the it only supports "SNP_6.0", "Illumina_WES", "SNP_250K_STY" platform. Can it be applied to Illumina_WGS platform? What's your suggestion?

**Comment by ShixiangWang** [comment]
Sorry for the late delay. I did not got this your message from my email.

The platform is same as the ABSOLUTE software itself. I did not see this "illumina_WGS" before. You may try "SNP_6.0" and "illumina_WES", and see what't the difference between them.
