### ISSUE TITLE
"Allelic" parameter error

### ISSUE THREAD

**Issue by joonan30** [ShixiangWang/DoAbsolute#20]
Hi Shixiang,

Thanks for the wonderful tool. I ran successfully with "total" parameter for the `copy.num.type` but when I set to "allelic", it does not work. The error message is:

```
> Checking result files...
-> Checked.
-> Removed previous temp review result directory.
-> Running Absolute summarize...
..............................Error in round(hscn.params[["sigma.eta"]], 3) : 
  non-numeric argument to mathematical function
```

Do you have any idea on this?

Best,
Joon

**Comment by ShixiangWang** [comment]
Hi @joonan30 ,

you can check https://software.broadinstitute.org/cancer/cga/absolute_run

![image](https://user-images.githubusercontent.com/25057508/150533841-3d611a3f-0412-4d6f-aa8e-4e338b746d93.png)

Best

**Comment by joonan30** [comment]
Thanks, it was my bad. My input is not for HAPSEG so it shouldn't work. 

Can I have another question? From the result, none of my samples (WES) was predicted to have "genome double" , which I assume some of samples would be. Do you think it's related to parameters or WES (or possibly no genome doubled samples) ? 

Thanks!!

**Comment by ShixiangWang** [comment]
@joonan30 I don't know. But you can try Sequenza or Facets to check the tumor genome ploidy. If truly a WGD, a ploidy value >= 4 (or close) should be observed.

**Comment by joonan30** [comment]
Thansk Shixiang, I was able to get it by facets. Many thanks for your time (and tool as well!!)

Best,
