### ISSUE TITLE
Error: the condition has length > 1

### ISSUE THREAD

**Issue by neuro30** [ShixiangWang/DoAbsolute#22]
HI, I tried running the example as written, but keep getting the following:

> Setting results directory as /home/comp/data/
-> Removed previous error log file.
-> Loading segmentation data...
-> Checking data format of segmentation file...
-> Keeping only chr 1-23 for CNV data...
-> Creating temp directory ...
-> Setting temp directory as /home/comp/data/temp 
-> Spliting seg data of samples to different files...
--> Processing sample  TCGA-DK-A1A6-10A-01D-A13V-01 ...
-> Spliting seg data of samples done.
-> Running RunAbsolute...(be patient)
--> Processing sample  TCGA-DK-A1A6-10A-01D-A13V-01 ...
[1] "Capping 0 segs at tCR = 5.0"
[1] "Expected copy-ratio = 1.00032"
[1] "MAF file:  not found."
.----> Error detected, see log for more details.
-> RunAbsolute done. Retrieving results...
--> Files in cache directory:
[1] "tmp"
-> Checking result files...
Warning in DoAbsolute(Seg = Seg, sigma.p = 0, max.sigma.h = 0.2, min.ploidy = 0.5,  :
  --> Result file /home/titancomp11/Documents/Methylation/data/Copy_number/ABSOLUTE/temp/cache/TCGA-DK-A1A6-10A-01D-A13V-01.ABSOLUTE.RData does not exist, drop it.
Error in DoAbsolute(Seg = Seg, sigma.p = 0, max.sigma.h = 0.2, min.ploidy = 0.5,  : 
  No result file to proceed.

Error file:
Detected error in sample TCGA-DK-A1A6-10A-01D-A13V-01 
Error message: the condition has length > 1 
Where:
if !is.na(res) {
    mode.tab[(i - 1) * n.d + j, ] <- c(res[[1]], res[[2]], res[[3]])
} 
Skipping this sample.

Running the core ABSOLUTE 1.0.6  package I get:
[1] "Capping 0 segs at tCR = 5.0"
[1] "Expected copy-ratio = 1.00032"
[1] "MAF file:  not found."
.Error in if (!is.na(res)) { : the condition has length > 1

**Comment by ShixiangWang** [comment]
could you reinstall the absolute？ see https://github.com/ShixiangWang/DoAbsolute/issues/21
