### ISSUE TITLE
What do the NA mean?

### ISSUE THREAD

**Issue by xiasijian** [ShixiangWang/DoAbsolute#27]
I am sorry if I troubled you again.
![image](https://user-images.githubusercontent.com/39158528/221339721-53f258d2-327d-4099-96ed-c9dd5cff4d3a.png)

There are some NA in purity and ploidy, does it appear that the somatic mutation and copy number is little?

**Comment by ShixiangWang** [comment]
有些数据它觉得质量不好或怎样就算不出来，相当于检测失败

**Comment by xiasijian** [comment]
好的，谢谢王老师~
