### ISSUE TITLE
DoAbsolute Error in mode.ent[i] <- mtab[ix, "entropy"] : replacement has length zero

### ISSUE THREAD

**Issue by tanayb001** [ShixiangWang/DoAbsolute#28]
Hello Wang,

I've encountered the following error while running DoAbsolute.

<html>
<body>

> DoAbsolute( "P2_seg.txt", Maf = "p2_maf.txt", primary.disease = "PRAD", platform = "Illumina_WES", temp.dir = "/Absolute", results.dir = "/P2", clean.temp = FALSE, copy.num.type = "total", verbose = TRUE) 

-> Setting results directory as /P2 
 -> Loading segmentation data... 
-> Loading Maf data... 
-> Checking data format of segmentation file...
-> Keeping only chr 1-23 for CNV data... 
-> Keeping only chr 1-23 for Maf data... 
-> Creating temp directory ... 
-> Setting temp directory as /Absolute  
-> Spliting seg data of samples to different files...
 --> Processing sample  P02-TD ... 
---> Filtering mutations which vaf< 0.1 ... 
---> Filtering Maf which count< 5 ... 
---> Outputing corresponding Maf file... 
-> Spliting seg data of samples done. Directory /Absolute/cache does not exists. 
-> Running RunAbsolute...(be patient) 
--> Processing sample  P02-TD ... [1] "Capping 0 segs at tCR = 5.0" [1] "Expected copy-ratio = 1.39699" [1] "Mode flag is NA, not generating plots. Sample has failed ABSOLUTE" 
-> RunAbsolute done. Retrieving results... 
--> Files in cache directory: [1] "P02-TD.ABSOLUTE.RData" "tmp"                       
 -> Checking result files... 
-> Checked. 
-> Running Absolute summarize... [1] "Failed list got updated 1" 
-Error in mode.ent[i] <- mtab[ix, "entropy"] : replacement has length zero

Can you please help me out with this. I'm not able to understand the problem. For the other few samples it is working fine.

Thank you.

Regards,
Tanay

**Comment by ShixiangWang** [comment]
Hi Tanay,

ABSOLUTE sometimes fails in some tumors. You could try call ABSOLUTE directly to check if it fails again. And if so, you may run DoAbsolute with only copy number data.

Best,

Shixiang

**Comment by tanayb001** [comment]
Hi Wang,

I ran ABSOLUTE and it is giving the following error:

> RunAbsolute("P2_seg.txt", sigma.p = 0, max.sigma.h = 0.2, + min.ploidy = 0.5,  max.ploidy = 10, sample.name = "P2", primary.disease = "PRAD", + platform = "Illumina_WES", results.dir = "D:/P2", + max.as.seg.count = 1500,  max.non.clonal = 0.05,  + max.neg.genome = 0.005,    copy_num_type = "total",  min.mut.af = 0.1, + verbose = TRUE) 
[1] "Capping 0 segs at tCR = 5.0"
[1] "Expected copy-ratio = 1.39678" 
[1] "Mode flag is NA, not generating plots. Sample has failed ABSOLUTE" 
[1] TRUE


Please let me know how to solve this. Previously in the failed samples mode.flag was showing E_CR_SCALE. 

Thank you.

Regards,
Tanay

**Comment by ShixiangWang** [comment]
Hi Tanay, in such a case I have no idea to make the ABSOLUTE get some value. On your side, I suggest you tune the parameters, i.e., loose the limits such as increase `max.sigma.h `.

**Comment by tanayb001** [comment]
Hi Wang,

It's not working even at the high value of max.sigma.h at 2-10.

**Comment by ShixiangWang** [comment]
I have no further suggestions. Maybe you should ask the authors of ABSOLUTE for some help.

**Comment by zhengyugitup** [comment]
Did you solve the problem? I have met the same problem with you.

**Comment by wangcongjian** [comment]
I encounter the same problem too.
