### ISSUE TITLE
Run DoAbsolute based on WES

### ISSUE THREAD

**Issue by WangKang-Leo** [ShixiangWang/DoAbsolute#29]
I prepare the input data for DoAbsolute, which included segment data from CNVkit and maf data from Mutect2. Should I prepare the maf data like PureCN:
Since germline SNPs are needed to infer allele-specific copy numbers, the provided VCF needs to contain both somatic and germline variants. Make sure that upstream filtering does not remove high quality SNPs, in particular due to presence in germline databases. Mutect 1.1.7 automatically calls SNPs, but Mutect 2 does not. Make sure to run Mutect 2 with --genotype-germline-sites true --genotype-pon-sites true. You will not get usuable output without those flags. (https://www.bioconductor.org/packages/devel/bioc/vignettes/PureCN/inst/doc/Quick.html#52_Recommended_CNVkit_usage)

Does DoAbsolute support GRCh38? I noticed the example data is GRCh37 based.

The last question is on whole genome doubling (WGB), I found all my output (200 BRCA samples) are 0....Do you know how to refine that?

**Comment by ShixiangWang** [comment]
- maf data from Mutect2 is fine.
- The DoAbsolute is not related to the genome build version. However, I don't know if the ABSOLUTE itself only supports hg19. In my personal view, the hg38 works fine if your input data are all hg38 based.
- For the WGB, sorry, I don't know how to refine that. You may need to check all input arguments of ABSOLUTE package from the firehose or R console.
