### ISSUE TITLE
to analyze purities using panel sequencing data 

### ISSUE THREAD

**Issue by h170607** [ShixiangWang/DoAbsolute#30]
Hi, @ShixiangWang 
We want to analyze the purity and ploidy of a set of tumor samples using panel sequencing data (over 700 genes). The segment files were from CNVkit and maf files were from Mutect2 and vcf2maf.
We are not sure if the platform parameter should use "SNP_6" or "Illumina_WES". Tried both options, and we found that several samples were 1 or 0.99 pure, ploidy was irregular, but some were above 7. Does this mean that some parameters are not suitable?
In addition, some purity results are quite different from those calculated by other software. Is this normal?

best,
Matt

**Comment by ShixiangWang** [comment]
For panel sequencing, I recommend you use the Sequenza or the latest version of ASCAT.

**Comment by h170607** [comment]
Thanks for your reply.
Do you mean that absolute and DoAbsolute are mainly suitable for analyzing wes and wgs data?
In addition, it seems that the broadinstitute no longer supports absolute, and the document and download links on genepattern is also invalid. Will this affect the subsequent use of absolute and DoAbsolute?

**Comment by ShixiangWang** [comment]
Yes. The ABSOLUTE did not say that it could handle target sequencing data, so I don't recommend it.

The use of DoAbsolute is not affected.

**Comment by h170607** [comment]
Could you please share the document of absolute mentioned in https://www.jianshu.com/p/468077752689, since the official link is invalid?

**Comment by ShixiangWang** [comment]
No. I haven't backup. I found only the link https://www.genepattern.org/analyzing-absolute-data#gsc.tab=0 works.

**Comment by h170607** [comment]
Thanks a lot
