### ISSUE TITLE
Error message: the condition has length > 1 

### ISSUE THREAD

**Issue by LoRner22** [ShixiangWang/DoAbsolute#33]
Dear sir,
  This error occured when I was use the test data，which also occurred when I tried to use ABSOLUTE to analyze single data.
I had checked my input data，but I couldn't find something wrong.
my code :

```

devtools::install_github("ShixiangWang/DoAbsolute")
library(DoAbsolute)
example_path = system.file("extdata", package = "DoAbsolute", mustWork = T)
library(data.table)
#segmentation文件
seg_normal =  file.path(example_path, "SNP6_blood_normal.seg.txt")
seg_solid  =  file.path(example_path, "SNP6_solid_tumor.seg.txt")
seg_metastatic  = file.path(example_path, "SNP6_metastatic_tumor.seg.txt")

maf_solid  = file.path(example_path, "solid_tumor.maf.txt")
maf_metastatic  = file.path(example_path, "metastatic_tumor.maf.txt")


seg_normal = fread(seg_normal)
seg_solid = fread(seg_solid)
seg_metastatic = fread(seg_metastatic)
maf_solid = fread(maf_solid)
maf_metastatic = fread(maf_metastatic)

Seg = Reduce(rbind, list(seg_normal, seg_solid, seg_metastatic))
Maf = Reduce(rbind, list(maf_solid, maf_metastatic))
Seg$Sample = substr(Seg$Sample, 1, 15)
Maf$Tumor_Sample_Barcode = substr(Maf$Tumor_Sample_Barcode, 1, 15) 

DoAbsolute(Seg = Seg, Maf = Maf,
           platform = "SNP_6.0",
           copy.num.type = "total",
           results.dir = "./a",
           nThread = 2,
           keepAllResult = TRUE,
           verbose = TRUE)
```

Seg:
![image](https://github.com/ShixiangWang/DoAbsolute/assets/95842447/773917d5-2b71-431e-9d3f-84defc328284)
Maf:
![image](https://github.com/ShixiangWang/DoAbsolute/assets/95842447/1f1d2495-603a-4b6e-9736-34504b2a202b)

Looking forward to your reply.
Sincerely,
Jesson Miao.

**Comment by ShixiangWang** [comment]
@LoRner22 Have you installed the ABSOLUTE with the following way?

```r
install.packages("numDeriv")
path_to_file = system.file("extdata", "ABSOLUTE_1.0.6.tar.gz", package = "DoAbsolute", mustWork = T)
install.packages(path_to_file, repos = NULL, type="source")
```

**Comment by LoRner22** [comment]
Thanks for your reply.
Sure,sir.And the two packages could be loaded successfully.

---- Replied Message ----
| From | Shixiang Wang ***@***.***> |
| Date | 05/05/2024 10:52 |
| To | ShixiangWang/DoAbsolute ***@***.***> |
| Cc | Jesson ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [ShixiangWang/DoAbsolute] Error message: the condition has length > 1 (Issue #33) |

@LoRner22 Have you installed the ABSOLUTE with the following way?

install.packages("numDeriv")
path_to_file= system.file("extdata", "ABSOLUTE_1.0.6.tar.gz", package="DoAbsolute", mustWork=T)
install.packages(path_to_file, repos=NULL, type="source")

**Comment by ShixiangWang** [comment]
What's your R version? Could you provide your R session?

```r
devtools::session_info()
```

**Comment by LoRner22** [comment]
I have tired the version 4.4.0，4.3.1 and 4.2.1，but the same error occurred. Is there a need for a even lower version？

---- Replied Message ----
| From | Shixiang Wang ***@***.***> |
| Date | 05/05/2024 12:27 |
| To | ShixiangWang/DoAbsolute ***@***.***> |
| Cc | Jesson ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [ShixiangWang/DoAbsolute] Error message: the condition has length > 1 (Issue #33) |

What's your R version? Could you provide your R session?

devtools::session_info()

**Comment by ShixiangWang** [comment]
Should work >4.0. I just tried in my MacBook pro, but it just fine.

```r
devtools::install_github("ShixiangWang/DoAbsolute")

install.packages("numDeriv")
path_to_file = system.file("extdata", "ABSOLUTE_1.0.6.tar.gz", package = "DoAbsolute", mustWork = T)
install.packages(path_to_file, repos = NULL, type="source")

library(DoAbsolute)

example_path = system.file("extdata", package = "DoAbsolute", mustWork = T)


library(data.table)
# Load Test Data ----------------------------------------------------------

# segmentation file
seg_normal =  file.path(example_path, "SNP6_blood_normal.seg.txt")
seg_solid  =  file.path(example_path, "SNP6_solid_tumor.seg.txt")
seg_metastatic  = file.path(example_path, "SNP6_metastatic_tumor.seg.txt")
# MAF file
maf_solid  = file.path(example_path, "solid_tumor.maf.txt")
maf_metastatic  = file.path(example_path, "metastatic_tumor.maf.txt")

# read data
seg_normal = fread(seg_normal)
seg_solid = fread(seg_solid)
seg_metastatic = fread(seg_metastatic)
maf_solid = fread(maf_solid)
maf_metastatic = fread(maf_metastatic)

# merge data
Seg = Reduce(rbind, list(seg_normal, seg_solid, seg_metastatic))
Maf = Reduce(rbind, list(maf_solid, maf_metastatic))

Seg$Sample = substr(Seg$Sample, 1, 15)
Maf$Tumor_Sample_Barcode = substr(Maf$Tumor_Sample_Barcode, 1, 15)

# test function
DoAbsolute(Seg = Seg, Maf = Maf, platform = "SNP_6.0", copy.num.type = "total",
           results.dir = "test", keepAllResult = TRUE, verbose = TRUE)


devtools::session_info()
```

**Comment by ShixiangWang** [comment]
Would you mind run the code above once again, and paste here anything printing to the R console?

**Comment by LoRner22** [comment]
Dear Wang,
I have run the code.The print information on the console was too long to recall so I could only copy some ending of them.(paste to the p.txt)
This time it works,producing corresponding files:




Also,I have tried to drop the R version to 4.0.5.The error under the former versions I used disappeared.All my own 24 datas worked successfully.So strange.


| |
xujie_miao
|
|
***@***.***
|
---- Replied Message ----
| From | Shixiang Wang ***@***.***> |
| Date | 5/5/2024 12:42 |
| To | ***@***.***> |
| Cc | Jesson ***@***.***> ,
***@***.***> |
| Subject | Re: [ShixiangWang/DoAbsolute] Error message: the condition has length > 1 (Issue #33) |

Would you mind run the code above once again, and paste here anything printing to the R console?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

$SC
Pr_subclonal 
  0.08360404 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.41353 0.43430 0.07457 0.02762 0.01719 0.00404 0.00293 0.00293 0.00293 0.00293 0.00293 0.00293 0.00294 0.00530 0.00293
$SM
Pr_somatic_clonal 
        0.8959114 

$GL
[1] 0

$SC
Pr_subclonal 
   0.1040886 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.46134 0.46705 0.01611 0.02306 0.00274 0.00274 0.00274 0.00274 0.00274 0.00274 0.00507 0.00274 0.00274 0.00274 0.00274
$SM
Pr_somatic_clonal 
        0.8573447 

$GL
[1] 0

$SC
Pr_subclonal 
   0.1426553 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.39434 0.42016 0.07587 0.05733 0.00688 0.01379 0.00320 0.00320 0.00320 0.00320 0.00320 0.00320 0.00321 0.00600 0.00320
$SM
Pr_somatic_clonal 
        0.9131441 

$GL
[1] 0

$SC
Pr_subclonal 
  0.08685587 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.55796 0.37670 0.02191 0.01112 0.00282 0.00269 0.00269 0.00269 0.00270 0.00526 0.00269 0.00269 0.00269 0.00269 0.00269
$SM
Pr_somatic_clonal 
        0.7794858 

$GL
[1] 0

$SC
Pr_subclonal 
   0.2205142 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.66425 0.28187 0.01178 0.00328 0.00328 0.00328 0.00328 0.00328 0.00605 0.00328 0.00328 0.00328 0.00328 0.00328 0.00328
$SM
Pr_somatic_clonal 
         0.830015 

$GL
[1] 0

$SC
Pr_subclonal 
    0.169985 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.70460 0.25463 0.00298 0.00298 0.00298 0.00298 0.00506 0.00298 0.00298 0.00298 0.00298 0.00298 0.00298 0.00298 0.00298
$SM
Pr_somatic_clonal 
        0.7731267 

$GL
[1] 0

$SC
Pr_subclonal 
   0.2268733 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.75330 0.19952 0.00355 0.00355 0.00355 0.00461 0.00355 0.00355 0.00355 0.00355 0.00355 0.00355 0.00355 0.00355 0.00355
$SM
Pr_somatic_clonal 
        0.7140579 

$GL
[1] 0

$SC
Pr_subclonal 
   0.2859421 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.78338 0.17359 0.00312 0.00312 0.00560 0.00312 0.00312 0.00312 0.00312 0.00312 0.00312 0.00312 0.00312 0.00312 0.00312
$SM
Pr_somatic_clonal 
        0.6288193 

$GL
[1] 0

$SC
Pr_subclonal 
   0.3711807 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.76735 0.18160 0.00370 0.00370 0.00659 0.00370 0.00370 0.00370 0.00370 0.00370 0.00370 0.00370 0.00370 0.00370 0.00370
$SM
Pr_somatic_clonal 
        0.6290502 

$GL
[1] 0

$SC
Pr_subclonal 
   0.3709498 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.76152 0.18838 0.00364 0.00364 0.00638 0.00364 0.00364 0.00364 0.00364 0.00364 0.00364 0.00364 0.00364 0.00364 0.00364
$SM
Pr_somatic_clonal 
        0.6582465 

$GL
[1] 0

$SC
Pr_subclonal 
   0.3417535 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.73814 0.20395 0.00795 0.00416 0.00416 0.00416 0.00416 0.00416 0.00416 0.00416 0.00416 0.00416 0.00416 0.00416 0.00416
$SM
Pr_somatic_clonal 
        0.4485609 

$GL
[1] 0

$SC
Pr_subclonal 
   0.5514391 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.75209 0.19337 0.00718 0.00395 0.00395 0.00395 0.00395 0.00395 0.00395 0.00395 0.00395 0.00395 0.00395 0.00395 0.00395
$SM
Pr_somatic_clonal 
        0.3617026 

$GL
[1] 0

$SC
Pr_subclonal 
   0.6382974 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.39025 0.41246 0.07351 0.06016 0.01406 0.01428 0.00585 0.00331 0.00331 0.00331 0.00331 0.00331 0.00331 0.00622 0.00331
$SM
Pr_somatic_clonal 
         0.919462 

$GL
[1] 0

$SC
Pr_subclonal 
  0.08053798 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.44925 0.43093 0.04796 0.00798 0.02510 0.00357 0.00356 0.00356 0.00356 0.00356 0.00356 0.00356 0.00356 0.00670 0.00356
$SM
Pr_somatic_clonal 
         0.901249 

$GL
[1] 0

$SC
Pr_subclonal 
  0.09875099 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.45442 0.43567 0.04540 0.00848 0.01944 0.00336 0.00336 0.00336 0.00336 0.00336 0.00336 0.00336 0.00337 0.00631 0.00336
$SM
Pr_somatic_clonal 
        0.8964434 

$GL
[1] 0

$SC
Pr_subclonal 
   0.1035566 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.47029 0.45911 0.00896 0.02377 0.00320 0.00320 0.00320 0.00320 0.00320 0.00320 0.00320 0.00320 0.00320 0.00590 0.00320
$SM
Pr_somatic_clonal 
        0.8849186 

$GL
[1] 0

$SC
Pr_subclonal 
   0.1150814 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.63443 0.30937 0.01489 0.00344 0.00344 0.00344 0.00344 0.00344 0.00344 0.00344 0.00344 0.00344 0.00344 0.00344 0.00344
$SM
Pr_somatic_clonal 
        0.8438519 

$GL
[1] 0

$SC
Pr_subclonal 
   0.1561481 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.68926 0.26087 0.01079 0.00305 0.00305 0.00305 0.00305 0.00305 0.00554 0.00305 0.00305 0.00305 0.00305 0.00305 0.00305
$SM
Pr_somatic_clonal 
          0.81374 

$GL
[1] 0

$SC
Pr_subclonal 
     0.18626 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.70474 0.25617 0.00312 0.00300 0.00300 0.00300 0.00300 0.00300 0.00300 0.00300 0.00300 0.00300 0.00300 0.00300 0.00300
$SM
Pr_somatic_clonal 
        0.7792655 

$GL
[1] 0

$SC
Pr_subclonal 
   0.2207345 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.74944 0.20402 0.00358 0.00358 0.00358 0.00358 0.00358 0.00358 0.00358 0.00358 0.00358 0.00358 0.00358 0.00358 0.00358
$SM
Pr_somatic_clonal 
        0.7382502 

$GL
[1] 0

$SC
Pr_subclonal 
   0.2617498 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.69739 0.23916 0.00488 0.00488 0.00488 0.00488 0.00488 0.00488 0.00488 0.00488 0.00488 0.00488 0.00488 0.00488 0.00488
$SM
Pr_somatic_clonal 
        0.5596631 

$GL
[1] 0

$SC
Pr_subclonal 
   0.4403369 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.68212 0.25123 0.00513 0.00513 0.00513 0.00513 0.00513 0.00513 0.00513 0.00513 0.00513 0.00513 0.00513 0.00513 0.00513
$SM
Pr_somatic_clonal 
        0.5790453 

$GL
[1] 0

$SC
Pr_subclonal 
   0.4209547 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.76842 0.18079 0.00369 0.00369 0.00652 0.00369 0.00369 0.00369 0.00369 0.00369 0.00369 0.00369 0.00369 0.00369 0.00369
$SM
Pr_somatic_clonal 
        0.6435261 

$GL
[1] 0

$SC
Pr_subclonal 
   0.3564739 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.46302 0.43536 0.03692 0.02088 0.01424 0.00271 0.00271 0.00271 0.00271 0.00271 0.00271 0.00522 0.00271 0.00271 0.00271
$SM
Pr_somatic_clonal 
        0.8562837 

$GL
[1] 0

$SC
Pr_subclonal 
   0.1437163 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.58882 0.34389 0.01895 0.00373 0.00373 0.00373 0.00373 0.00373 0.00373 0.00373 0.00374 0.00726 0.00373 0.00373 0.00373
$SM
Pr_somatic_clonal 
        0.8649597 

$GL
[1] 0

$SC
Pr_subclonal 
   0.1350403 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.57573 0.37288 0.01644 0.00489 0.00273 0.00273 0.00273 0.00273 0.00273 0.00273 0.00273 0.00273 0.00273 0.00273 0.00273
$SM
Pr_somatic_clonal 
        0.7664361 

$GL
[1] 0

$SC
Pr_subclonal 
   0.2335639 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.76184 0.19693 0.00304 0.00304 0.00304 0.00304 0.00470 0.00304 0.00304 0.00304 0.00304 0.00304 0.00304 0.00304 0.00304
$SM
Pr_somatic_clonal 
         0.718349 

$GL
[1] 0

$SC
Pr_subclonal 
    0.281651 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.44919 0.42790 0.04846 0.00797 0.02621 0.00415 0.00366 0.00366 0.00366 0.00366 0.00366 0.00366 0.00366 0.00687 0.00366
$SM
Pr_somatic_clonal 
        0.9041641 

$GL
[1] 0

$SC
Pr_subclonal 
  0.09583594 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.36907 0.35486 0.02432 0.06110 0.07139 0.04486 0.02809 0.01410 0.00598 0.00679 0.00331 0.00331 0.00331 0.00619 0.00331
$SM
Pr_somatic_clonal 
        0.9321067 

$GL
[1] 0

$SC
Pr_subclonal 
  0.06789334 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.49748 0.41563 0.02086 0.02742 0.00958 0.00278 0.00266 0.00266 0.00266 0.00266 0.00277 0.00486 0.00266 0.00266 0.00266
$SM
Pr_somatic_clonal 
        0.8304358 

$GL
[1] 0

$SC
Pr_subclonal 
   0.1695642 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.73112 0.22485 0.00317 0.00317 0.00597 0.00317 0.00317 0.00317 0.00317 0.00317 0.00317 0.00317 0.00317 0.00317 0.00317
$SM
Pr_somatic_clonal 
        0.5457939 

$GL
[1] 0

$SC
Pr_subclonal 
   0.4542061 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.41798 0.42242 0.04603 0.03625 0.02627 0.01997 0.00605 0.00296 0.00280 0.00280 0.00280 0.00306 0.00499 0.00280 0.00280
$SM
Pr_somatic_clonal 
        0.8872751 

$GL
[1] 0

$SC
Pr_subclonal 
   0.1127249 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.42485 0.43229 0.03885 0.03026 0.02817 0.01697 0.00426 0.00275 0.00274 0.00274 0.00275 0.00300 0.00489 0.00274 0.00274
$SM
Pr_somatic_clonal 
        0.8810088 

$GL
[1] 0

$SC
Pr_subclonal 
   0.1189912 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.45190 0.43344 0.02816 0.02736 0.02343 0.00871 0.00275 0.00271 0.00271 0.00271 0.00271 0.00296 0.00502 0.00271 0.00271
$SM
Pr_somatic_clonal 
        0.8631397 

$GL
[1] 0

$SC
Pr_subclonal 
   0.1368603 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.39518 0.40905 0.04986 0.05235 0.02905 0.02295 0.01578 0.00359 0.00289 0.00289 0.00289 0.00315 0.00458 0.00289 0.00289
$SM
Pr_somatic_clonal 
        0.9020224 

$GL
[1] 0

$SC
Pr_subclonal 
  0.09797764 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.57772 0.36127 0.01991 0.00907 0.00279 0.00271 0.00271 0.00272 0.00480 0.00271 0.00271 0.00271 0.00271 0.00271 0.00271
$SM
Pr_somatic_clonal 
        0.7620057 

$GL
[1] 0

$SC
Pr_subclonal 
   0.2379943 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.63175 0.31012 0.02115 0.00480 0.00282 0.00282 0.00282 0.00397 0.00282 0.00282 0.00282 0.00282 0.00282 0.00282 0.00282
$SM
Pr_somatic_clonal 
        0.7142293 

$GL
[1] 0

$SC
Pr_subclonal 
   0.2857707 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.45329 0.43463 0.02744 0.02595 0.02314 0.00867 0.00273 0.00270 0.00270 0.00270 0.00270 0.00295 0.00500 0.00270 0.00270
$SM
Pr_somatic_clonal 
         0.861933 

$GL
[1] 0

$SC
Pr_subclonal 
    0.138067 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.72984 0.21368 0.00407 0.00765 0.00407 0.00407 0.00407 0.00407 0.00407 0.00407 0.00407 0.00407 0.00407 0.00407 0.00407
$SM
Pr_somatic_clonal 
        0.3290336 

$GL
[1] 0

$SC
Pr_subclonal 
   0.6709664 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.61972 0.30083 0.00611 0.00611 0.00611 0.00611 0.00611 0.00611 0.00611 0.00611 0.00611 0.00611 0.00611 0.00611 0.00611
$SM
Pr_somatic_clonal 
       0.08670853 

$GL
[1] 0

$SC
Pr_subclonal 
   0.9132915 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.61766 0.30246 0.00614 0.00614 0.00614 0.00614 0.00614 0.00614 0.00614 0.00614 0.00614 0.00614 0.00614 0.00614 0.00614
$SM
Pr_somatic_clonal 
       0.08123675 

$GL
[1] 0

$SC
Pr_subclonal 
   0.9187633 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.61766 0.30246 0.00614 0.00614 0.00614 0.00614 0.00614 0.00614 0.00614 0.00614 0.00614 0.00614 0.00614 0.00614 0.00614
$SM
Pr_somatic_clonal 
       0.07705511 

$GL
[1] 0

$SC
Pr_subclonal 
   0.9229449 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.69683 0.25705 0.01058 0.00294 0.00294 0.00294 0.00323 0.00294 0.00294 0.00294 0.00294 0.00294 0.00294 0.00294 0.00294
$SM
Pr_somatic_clonal 
         0.643543 

$GL
[1] 0

$SC
Pr_subclonal 
    0.356457 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.56450 0.38500 0.01523 0.00276 0.00276 0.00276 0.00276 0.00276 0.00490 0.00276 0.00276 0.00276 0.00276 0.00276 0.00276
$SM
Pr_somatic_clonal 
        0.8053071 

$GL
[1] 0

$SC
Pr_subclonal 
   0.1946929 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.som_theta_Q_MAP:  [1] 0.75042 0.20422 0.00347 0.00327 0.00594 0.00327 0.00327 0.00327 0.00327 0.00327 0.00327 0.00327 0.00327 0.00327 0.00327
$SM
Pr_somatic_clonal 
        0.5144962 

$GL
[1] 0

$SC
Pr_subclonal 
   0.4855038 

$OL
[1] 0.001

$Pi_SM
[1] 15

$Pi_SC
[1] 15

.
-> RunAbsolute done. Retrieving results...
--> Files in cache directory:
[1] "TCGA-DK-A1A6-01.ABSOLUTE.RData"    "TCGA-DK-A1A6-01.ABSOLUTE_plot.pdf" "TCGA-DK-A1A6-06.ABSOLUTE.RData"   
[4] "TCGA-DK-A1A6-06.ABSOLUTE_plot.pdf" "TCGA-DK-A1A6-10.ABSOLUTE.RData"    "TCGA-DK-A1A6-10.ABSOLUTE_plot.pdf"
[7] "tmp"                              
-> Checking result files...
-> Checked.
-> Running Absolute summarize...
...
-> Absolute summarize done. Prepare auto-reviewing...
-> Absolute Auto-reviewing done.
-> Outputing final results...
--> Choose keeping all results...
Directory test/seg does not exists.
Directory test/maf does not exists.
--> Copying DoAbsolute files in review dir to result directory...
--> Copying  C:\Users\MIAOCU~1\AppData\Local\Temp\RtmpO6Tman/Absolute/cache/review/reviewed/SEG_MAF/TCGA-DK-A1A6-01.segtab.txt, C:\Users\MIAOCU~1\AppData\Local\Temp\RtmpO6Tman/Absolute/cache/review/reviewed/SEG_MAF/TCGA-DK-A1A6-06.segtab.txt to test/seg ...
--> Copying  C:\Users\MIAOCU~1\AppData\Local\Temp\RtmpO6Tman/Absolute/cache/review/reviewed/SEG_MAF/TCGA-DK-A1A6-01_ABS_MAF.txt, C:\Users\MIAOCU~1\AppData\Local\Temp\RtmpO6Tman/Absolute/cache/review/reviewed/SEG_MAF/TCGA-DK-A1A6-06_ABS_MAF.txt to test/maf ...
Directory test/summary does not exists.
Directory test/sample_before_summary does not exists.
Directory test/sample_final_called does not exists.

**Comment by ShixiangWang** [comment]
It should be the installation problem of a correct ABSOLUTE version. I am closing this now. Please file another issue if you found new use problem.
