### ISSUE TITLE
ERROR: "No mutations left"

### ISSUE THREAD

**Issue by taoziyu97** [ShixiangWang/DoAbsolute#9]
there are 9 cancers get back error messages after run DoABSOLUTE. It maybe something wrong in calling ABSOLUTE.

```
Error in { : task 145 failed - "No mutations left"
Calls: DoAbsolute -> %dopar% -> <Anonymous>
Execution halted
```

**Comment by ShixiangWang** [comment]
重新安装下 GitHub 上的 DoAbsolute 包，然后用报错的癌症，如 LUAD 试一下修改后的程序能否让程序正常运行。
